"""
Unit Tests and Verification Suite for ControlPlane.ai Cost Model & Checker Node.
"""

import unittest
from cost_engine import default_cost_engine, cost_checker_node
from pricing_catalog import get_model_pricing


class TestCostEvaluationEngine(unittest.TestCase):

    def test_model_pricing_catalog(self):
        pricing = get_model_pricing("gemini-1.5-pro")
        self.assertEqual(pricing.input_cost_per_million, 3.50)
        self.assertEqual(pricing.output_cost_per_million, 10.50)

        pricing_flash = get_model_pricing("gemini-1.5-flash")
        self.assertEqual(pricing_flash.input_cost_per_million, 0.075)

    def test_scenario_1_efficient_flash_call(self):
        """Standard efficient call using Gemini 1.5 Flash."""
        state = {
            "user_prompt": "What is the capital of France?",
            "source_documents": [],
            "llm_response": "The capital of France is Paris.",
            "model_name": "gemini-1.5-flash",
            "input_tokens": 12,
            "output_tokens": 8
        }
        res = default_cost_engine.evaluate(state)
        self.assertEqual(res.status, "PASS")
        self.assertGreaterEqual(res.cost_score, 90.0)
        self.assertLess(res.total_cost_usd, 0.0001)
        self.assertEqual(len(res.budget_eval.anomalies), 0)

    def test_scenario_2_rag_with_pdf_and_ocr(self):
        """RAG query with PDF and chart OCR using Gemini 1.5 Pro (Developer Setup Guide example)."""
        state = {
            "user_prompt": "Summarize the key findings from our Q3 compliance policy and risk chart.",
            "source_documents": [
                {"filename": "policy.pdf", "content": "Policy overview... " * 100},
                {"filename": "chart.png", "content": "Chart metrics... " * 50}
            ],
            "llm_response": "Here is the summary of Q3 findings: The policy requires strict audit logging...",
            "model_name": "gemini-1.5-pro",
            "input_tokens": 150,
            "output_tokens": 45
        }
        res = default_cost_engine.evaluate(state)
        self.assertGreater(res.tools_cost_usd, 0.0)
        self.assertIn("ocr_pdf", res.cost_breakdown.tool_cost_details)
        self.assertIn("ocr_image", res.cost_breakdown.tool_cost_details)
        self.assertGreater(res.cost_score, 60.0)

    def test_scenario_3_model_routing_overkill_flag(self):
        """Expensive model (Gemini Pro) used for a trivial 5-word request."""
        state = {
            "user_prompt": "Hi",
            "source_documents": [],
            "llm_response": "Hello there!",
            "model_name": "gemini-1.5-pro",
            "input_tokens": 2,
            "output_tokens": 3
        }
        res = default_cost_engine.evaluate(state)
        anomaly_types = [a.anomaly_type for a in res.budget_eval.anomalies]
        self.assertIn("MODEL_ROUTING_OVERKILL", anomaly_types)
        self.assertEqual(res.status, "FLAG")

    def test_scenario_4_runaway_loop_anomaly(self):
        """Runaway token generation loop detection."""
        looping_text = "Repeat this exact phrase forever. " * 80
        state = {
            "user_prompt": "Generate a short summary",
            "source_documents": [],
            "llm_response": looping_text,
            "model_name": "gemini-1.5-pro",
            "input_tokens": 10,
            "output_tokens": 600
        }
        res = default_cost_engine.evaluate(state)
        self.assertEqual(res.status, "CRITICAL")
        anomaly_types = [a.anomaly_type for a in res.budget_eval.anomalies]
        self.assertIn("RUNAWAY_GENERATION_LOOP", anomaly_types)

    def test_scenario_5_budget_ceiling_breach(self):
        """Hard budget ceiling breach with massive input context."""
        state = {
            "user_prompt": "Analyze everything",
            "source_documents": [],
            "llm_response": "Analysis output..." * 500,
            "model_name": "gemini-1.5-pro",
            "input_tokens": 150_000,
            "output_tokens": 8_000
        }
        res = default_cost_engine.evaluate(state)
        self.assertEqual(res.status, "CRITICAL")
        self.assertTrue(res.budget_eval.is_budget_exceeded)
        self.assertEqual(res.budget_eval.budget_compliance_score, 0.0)

    def test_scenario_6_langgraph_node_integration(self):
        """Verify seamless state dictionary mutation for LangGraph orchestrator."""
        input_state = {
            "user_prompt": "The text the user typed",
            "source_documents": [
                {"filename": "policy.pdf", "content": "Extracted plain text..."},
                {"filename": "chart.png", "content": "Extracted OCR text..."}
            ],
            "llm_response": "The text generated by Gemini",
            "model_name": "gemini-1.5-pro",
            "input_tokens": 150,
            "output_tokens": 45
        }
        output_state = cost_checker_node(input_state)
        self.assertIn("cost_agent", output_state)
        self.assertIn("score", output_state["cost_agent"])
        self.assertIn("status", output_state["cost_agent"])
        self.assertIn("total_cost_usd", output_state["cost_agent"])
        print("\n[LangGraph Node Output Test]:", output_state["cost_agent"])


if __name__ == "__main__":
    unittest.main()
